import { StyleSheet, Platform, Dimensions } from "react-native";
import { SHEET_BOTTOM_OFFSET, FLOATING_CARD_BOTTOM_OFFSET } from "./types";
const { height: SCREEN_HEIGHT } = Dimensions.get("window");
export const getStyles = (COLORS: any, isDark: boolean) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.background },
    map: { flex: 1, width: "100%" },
    loader: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: COLORS.background,
    },
    loaderText: {
      marginTop: 12,
      color: COLORS.textSecondary,
      fontWeight: "600",
    },

    // ── Unified Top Navigation ──────────────────────────────────────────────
    topContainer: {
      position: "absolute",
      left: 0,
      right: 0,
      paddingHorizontal: 16,
      zIndex: 8000,
      elevation: 40,
    },
    pageControlFloating: {
      alignSelf: "flex-end",
    },
    floatingSearchStack: {
      gap: 6,
      zIndex: 12,
      alignItems: "flex-end",
    },
    floatingSearchBar: {
      flexDirection: "row",
      alignItems: "center",
      height: 44,
      borderRadius: 999,
      paddingHorizontal: 6,
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(12,12,14,0.08)",
      backgroundColor: isDark ? "rgba(20,20,22,0.85)" : "rgba(255,255,255,0.92)",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 10,
      elevation: 10,
      width: "100%",
      marginRight: 6,
    },
    searchLeadingIcon: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: "center",
      justifyContent: "center",
    },
    floatingSearchPrompt: {
      flex: 1,
      justifyContent: "center",
      paddingVertical: 12,
    },
    floatingSearchPromptText: {
      color: COLORS.textTertiary,
      fontSize: 13,
      fontWeight: "600",
    },
    floatingSearchInput: {
      flex: 1,
      color: COLORS.textPrimary,
      fontSize: 13,
      fontWeight: "600",
      paddingVertical: 0,
      paddingHorizontal: 4,
    },
    searchTrailingButton: {
      minWidth: 36,
      height: 36,
      borderRadius: 18,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 4,
    },
    searchCancelText: {
      color: COLORS.textPrimary,
      fontSize: 13,
      fontWeight: "700",
    },
    viewMenuTrigger: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      minHeight: 34,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: isDark ? "#27272A" : "#DADCE0",
      backgroundColor: isDark ? "#141416" : "#FFFFFF",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 6,
    },
    viewMenuTriggerText: {
      color: COLORS.textPrimary,
      fontSize: 12,
      fontWeight: "800",
    },
    viewDropdownMenu: {
      minWidth: 132,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: isDark ? "#27272A" : "#DADCE0",
      backgroundColor: isDark ? "#141416" : "#FFFFFF",
      overflow: "hidden",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 10,
      elevation: 8,
    },
    searchResults: {
      position: "absolute",
      top: 162,
      left: 16,
      right: 16,
      backgroundColor: isDark ? "#1C1C1E" : "#FFFFFF",
      borderRadius: 16,
      padding: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.2,
      shadowRadius: 20,
      elevation: 10,
      zIndex: 100,
      maxHeight: "60%",
    },
    viewDropdownItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    searchItem: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 14,
      paddingVertical: 13,
      borderBottomWidth: 1,
      borderBottomColor: "rgba(255,255,255,0.06)",
      gap: 12,
    },
    searchItemName: { fontSize: 15, fontWeight: "600" },
    searchItemSub: { fontSize: 12, color: COLORS.textSecondary, marginTop: 3 },
    searchSectionLabel: {
      fontSize: 10,
      fontWeight: "800",
      letterSpacing: 0.8,
      textTransform: "uppercase",
      color: COLORS.textTertiary,
      paddingHorizontal: 14,
      paddingTop: 12,
      paddingBottom: 6,
    },
    layerPillRail: {
      marginHorizontal: -4,
      zIndex: 6,
    },
    layerPillScrollerContent: {
      paddingHorizontal: 4,
      gap: 8,
    },
    layerPill: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 11,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: isDark ? "#141416" : "#FFFFFF",
      borderWidth: 1,
      borderColor: isDark ? "#27272A" : "#DADCE0",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
      elevation: 4,
    },
    layerPillActive: {
      backgroundColor: "#500000",
      borderColor: "#500000",
    },
    layerPillText: {
      color: COLORS.textPrimary,
      fontSize: 11,
      fontWeight: "800",
    },
    layerPillTextActive: {
      color: "#FFFFFF",
    },
    layerSettingsPill: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 11,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: isDark ? "#141416" : "#FFFFFF",
      borderWidth: 1,
      borderStyle: "dashed",
      borderColor: isDark ? "#3A3A3D" : "#C7CBD1",
    },
    layerSettingsPillText: {
      color: COLORS.textPrimary,
      fontSize: 11,
      fontWeight: "800",
    },
    scheduleHeaderCard: {
      borderRadius: 24,
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(12,12,14,0.08)",
      backgroundColor: isDark ? "rgba(14,14,16,0.9)" : "rgba(255,255,255,0.94)",
      padding: 16,
      gap: 14,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.2,
      shadowRadius: 14,
      elevation: 10,
    },
    scheduleHeaderTopRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 12,
    },
    scheduleHeaderEyebrow: {
      color: COLORS.textSecondary,
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.7,
      marginBottom: 4,
    },
    scheduleHeaderTitle: {
      color: COLORS.textPrimary,
      fontSize: 18,
      fontWeight: "800",
      marginBottom: 4,
    },
    scheduleHeaderBody: {
      color: COLORS.textSecondary,
      fontSize: 13,
      lineHeight: 19,
    },
    scheduleHeaderButton: {
      minHeight: 38,
      paddingHorizontal: 14,
      borderRadius: 19,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#500000",
    },
    scheduleHeaderButtonText: {
      color: "#FFFFFF",
      fontSize: 12,
      fontWeight: "800",
    },
    scheduleChipScroller: {
      gap: 10,
      paddingRight: 4,
    },
    scheduleChip: {
      minWidth: 148,
      maxWidth: 224,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(12,12,14,0.08)",
      backgroundColor: isDark ? "#121214" : "#F6F4F1",
      gap: 4,
    },
    scheduleChipActive: {
      backgroundColor: "#500000",
      borderColor: "#500000",
    },
    scheduleChipLabel: {
      color: COLORS.textPrimary,
      fontSize: 13,
      fontWeight: "800",
    },
    scheduleChipLabelActive: {
      color: "#FFFFFF",
    },
    scheduleChipMeta: {
      color: COLORS.textSecondary,
      fontSize: 11,
      fontWeight: "600",
    },
    scheduleChipMetaActive: {
      color: "rgba(255,255,255,0.82)",
    },
    scheduleHeaderFooter: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    scheduleHeaderFooterText: {
      color: COLORS.textSecondary,
      fontSize: 12,
      fontWeight: "700",
      flex: 1,
    },
    scheduleEmptyState: {
      borderRadius: 20,
      padding: 14,
      gap: 12,
      backgroundColor: isDark ? "#121214" : "#F6F4F1",
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.06)" : "rgba(12,12,14,0.06)",
    },
    scheduleEmptyStateTitle: {
      color: COLORS.textPrimary,
      fontSize: 15,
      fontWeight: "800",
    },
    scheduleEmptyStateBody: {
      color: COLORS.textSecondary,
      fontSize: 13,
      lineHeight: 19,
    },
    scheduleEmptyActionRow: {
      flexDirection: "row",
      gap: 10,
    },
    scheduleEmptyAction: {
      flex: 1,
      minHeight: 42,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(12,12,14,0.08)",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: isDark ? "#18181A" : "#FFFFFF",
      paddingHorizontal: 12,
    },
    scheduleEmptyActionPrimary: {
      backgroundColor: "#500000",
      borderColor: "#500000",
    },
    scheduleEmptyActionText: {
      color: COLORS.textPrimary,
      fontSize: 13,
      fontWeight: "800",
    },
    scheduleEmptyActionPrimaryText: {
      color: "#FFFFFF",
      fontSize: 13,
      fontWeight: "800",
    },
    timelineContainer: {
      paddingVertical: 18,
      paddingHorizontal: 14,
      position: "relative",
    },
    timelineLine: {
      position: "absolute",
      left: 88,
      top: 0,
      bottom: 0,
      width: 2,
      backgroundColor: isDark ? "rgba(255,255,255,0.06)" : "rgba(12,12,14,0.04)",
    },
    timelineItem: {
      flexDirection: "row",
      marginBottom: 22,
    },
    timelineTimeCol: {
      width: 72,
      alignItems: "flex-end",
      paddingRight: 12,
      paddingTop: 2,
    },
    timelineTimeText: {
      fontSize: 12,
      fontWeight: "800",
      color: COLORS.textPrimary,
      opacity: 0.8,
    },
    timelineDotCol: {
      width: 32,
      alignItems: "center",
      paddingTop: 6,
    },
    timelineDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      borderWidth: 2,
      borderColor: isDark ? "#121214" : "#FFFFFF",
    },
    timelineContentCol: {
      flex: 1,
      paddingLeft: 6,
    },
    timelineCard: {
      backgroundColor: isDark ? "rgba(255,255,255,0.03)" : "rgba(12,12,14,0.03)",
      borderRadius: 16,
      padding: 14,
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.05)" : "rgba(12,12,14,0.05)",
    },
    timelineHeaderRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      gap: 8,
    },
    timelineTitle: {
      fontSize: 15,
      fontWeight: "800",
      color: COLORS.textPrimary,
      marginBottom: 2,
    },
    timelineLocation: {
      fontSize: 13,
      fontWeight: "600",
      color: COLORS.textSecondary,
    },
    timelineBadge: {
      paddingHorizontal: 7,
      paddingVertical: 3,
      borderRadius: 6,
      backgroundColor: isDark ? "rgba(255,255,255,0.06)" : "rgba(12,12,14,0.06)",
    },
    timelineBadgeText: {
      fontSize: 10,
      fontWeight: "900",
      letterSpacing: 0.5,
      color: COLORS.textTertiary,
    },
    timelineActionButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginTop: 10,
    },
    timelineActionText: {
      fontSize: 12,
      fontWeight: "800",
      color: "#007AFF",
    },

    // ── Pins ────────────────────────────────────────────────────────────────
    pinContainer: { alignItems: "center", justifyContent: "center" },
    pinHead: {
      width: 38,
      height: 38,
      borderRadius: 19,
      borderWidth: 2,
      borderColor: "#FFF",
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.5,
      shadowRadius: 4,
      elevation: 6,
    },
    pinInnerCircle: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: "rgba(255,255,255,0.1)",
      alignItems: "center",
      justifyContent: "center",
    },
    pinTail: {
      width: 0,
      height: 0,
      backgroundColor: "transparent",
      borderStyle: "solid",
      borderLeftWidth: 8,
      borderRightWidth: 8,
      borderTopWidth: 12,
      borderLeftColor: "transparent",
      borderRightColor: "transparent",
      marginTop: -3,
    },

    // ── Bottom Sheet ────────────────────────────────────────────────────────
    bottomSheet: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: SHEET_BOTTOM_OFFSET + 10,
      height: SCREEN_HEIGHT * 0.85,
      backgroundColor: isDark ? "rgba(12,12,12,0.96)" : "rgba(255,255,255,0.95)",
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      borderTopWidth: 1,
      borderTopColor: isDark ? "#1F1F1F" : "rgba(12,12,14,0.08)",
      paddingHorizontal: 18,
      paddingTop: 10,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -6 },
      shadowOpacity: 0.5,
      shadowRadius: 20,
      elevation: 40,
      zIndex: 7000,
      overflow: "hidden",
    },
    dragHandle: {
      width: 36,
      height: 4,
      borderRadius: 2,
      backgroundColor: isDark ? "#333" : "rgba(12,12,14,0.14)",
      alignSelf: "center",
      marginBottom: 14,
    },
    sheetHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      marginBottom: 10,
      gap: 10,
    },
    locationName: {
      fontSize: 22,
      fontWeight: "800",
      color: COLORS.textPrimary,
      lineHeight: 28,
      marginBottom: 3,
    },
    sheetBadgeRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    typeTextSlim: {
      color: COLORS.textSecondary,
      fontSize: 13,
      fontWeight: "600",
      textTransform: "capitalize",
    },
    dotSeparator: {
      color: isDark ? "#555" : "rgba(12,12,14,0.32)",
      fontSize: 14,
      marginHorizontal: 2,
    },
    liveBadgeSlim: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    liveTextSlim: { color: "#32D74B", fontSize: 12, fontWeight: "700" },
    aiBadgeSlim: { flexDirection: "row", alignItems: "center", gap: 6 },
    aiTextSlim: { color: COLORS.textSecondary, fontSize: 12, fontWeight: "600" },
    livePulse: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: "#32D74B",
    },
    dismissBtn: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: isDark ? "#1C1C1C" : "#F3F4F7",
      alignItems: "center",
      justifyContent: "center",
      marginTop: 2,
    },
    descriptionText: {
      color: COLORS.textSecondary,
      fontSize: 13,
      lineHeight: 18,
      marginBottom: 12,
    },
    quickActionRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginBottom: 12,
    },
    quickActionPill: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 8,
      backgroundColor: isDark ? "#161616" : "#F6F7FA",
      borderWidth: 1,
      borderColor: isDark ? "#262626" : "rgba(12,12,14,0.08)",
    },
    quickActionPrimary: {
      backgroundColor: "#500000",
      borderColor: "#500000",
    },
    quickActionText: {
      color: isDark ? "#F3F1ED" : COLORS.textPrimary,
      fontSize: 11,
      fontWeight: "800",
    },
    quickActionPrimaryText: {
      color: "#FFFFFF",
      fontSize: 11,
      fontWeight: "800",
    },
    contextCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: isDark ? "#252525" : "rgba(12,12,14,0.08)",
      backgroundColor: isDark ? "#131313" : "#F8F9FB",
      padding: 12,
      marginBottom: 12,
    },
    contextCardTitle: {
      color: COLORS.textPrimary,
      fontSize: 13,
      fontWeight: "800",
      marginBottom: 6,
    },
    contextCardBody: {
      color: COLORS.textSecondary,
      fontSize: 13,
      lineHeight: 18,
    },

    occupancyBlock:  { marginBottom: 8, backgroundColor: isDark ? '#161616' : '#F8F9FB', padding: 16, borderRadius: 16, borderWidth: 1, borderColor: isDark ? '#222' : 'rgba(12,12,14,0.08)' },
    occupancyHeaderRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
    occupancyLiveLabel: { fontSize: 13, color: '#AAA', fontWeight: '600', marginBottom: 2 },
    occupancyLiveText: { fontSize: 16, fontWeight: '800' },
    occupancyTrack:  {
        height: 6, backgroundColor: 'rgba(255,255,255,0.08)',
        borderRadius: 3, overflow: 'hidden', marginBottom: 16,
    },
    occupancyFill:   { height: '100%', borderRadius: 3 },

    hoursInfo: { flexDirection: "row", alignItems: "center", gap: 8 },
    hoursText: { fontSize: 14, color: COLORS.textSecondary, fontWeight: "600" },
    hoursInfoBlock: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 16 },
    inlineLinkRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginTop: 14,
    },
    inlineLinkText: {
      color: COLORS.textPrimary,
      fontSize: 12,
      fontWeight: "700",
    },
    metaPillRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
      marginTop: 12,
    },
    metaPill: {
      backgroundColor: isDark ? "#161616" : "#F5F6F8",
      borderRadius: 999,
      borderWidth: 1,
      borderColor: isDark ? "#262626" : "rgba(12,12,14,0.08)",
      paddingHorizontal: 10,
      paddingVertical: 7,
    },
    metaPillText: {
      color: isDark ? "#D6D6D6" : COLORS.textPrimary,
      fontSize: 11,
      fontWeight: "700",
    },

    sheetDivider: { height: 1, backgroundColor: isDark ? "#1C1C1C" : "rgba(12,12,14,0.08)", marginBottom: 14 },

    chartContainer: { marginBottom: 24 },
    chartTitle: {
      fontSize: 12,
      color: COLORS.textTertiary,
      fontWeight: "600",
      marginBottom: 12,
    },
    chartBars: {
      flexDirection: "row",
      alignItems: "flex-end",
      justifyContent: "space-between",
      height: 45,
    },
    barWrapper: {
      width: 12,
      height: 45,
      backgroundColor: "rgba(255,255,255,0.06)",
      borderRadius: 4,
      overflow: "hidden",
      justifyContent: "flex-end",
    },
    barFill: { width: "100%", borderRadius: 2 },

    sectionTitle: {
      fontSize: 12,
      color: COLORS.textSecondary,
      fontWeight: "700",
      marginBottom: 10,
      letterSpacing: 0.5,
      textTransform: "uppercase",
    },
    reviewItem: {
      paddingVertical: 12,
      borderTopWidth: 1,
      borderTopColor: isDark ? "#1C1C1C" : "rgba(12,12,14,0.08)",
    },
    reviewMeta: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 6,
    },
    reviewUser: { fontSize: 14, fontWeight: "700", color: COLORS.textPrimary },
    reviewUserRow: { flexDirection: "row", alignItems: "center", gap: 8 },
    userAvatar: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: "#333",
      alignItems: "center",
      justifyContent: "center",
    },
    avatarText: { color: "#AAA", fontSize: 10, fontWeight: "800" },
    reviewStars: { flexDirection: "row", gap: 3 },
    reviewComment: { fontSize: 13, color: COLORS.textSecondary, lineHeight: 18 },

    infoBlock: { marginBottom: 18 },
    detailTabsWrap: {
      marginBottom: 14,
    },
    menuIntroText: {
      color: COLORS.textTertiary,
      fontSize: 11,
      fontWeight: "600",
      marginTop: 3,
    },
    restaurantChipList: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 7,
      marginBottom: 14,
    },
    restaurantChip: {
      backgroundColor: isDark ? "#1A1A1A" : "#F5F6F8",
      paddingHorizontal: 11,
      paddingVertical: 7,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: isDark ? "#333" : "rgba(12,12,14,0.08)",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
    },
    restaurantChipActive: {
      borderColor: COLORS.primary,
      backgroundColor: "rgba(80,0,0,0.28)",
    },
    restaurantChipText: { color: isDark ? "#FFF" : COLORS.textPrimary, fontSize: 12, fontWeight: "700" },
    menuCategoryList: { marginBottom: 14, gap: 10 },
    menuCategoryCard: {
      backgroundColor: isDark ? "#111" : "#FFFFFF",
      borderRadius: 16,
      padding: 12,
      borderWidth: 1,
      borderColor: isDark ? "#222" : "rgba(12,12,14,0.08)",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.18,
      shadowRadius: 10,
      elevation: 4,
    },
    menuCategoryHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 8,
    },
    menuCategoryTitle: {
      color: COLORS.textPrimary,
      fontSize: 13,
      fontWeight: "900",
      letterSpacing: 0.2,
    },
    menuCategoryCount: {
      color: COLORS.textSecondary,
      fontSize: 11,
      fontWeight: "800",
      backgroundColor: isDark ? "#1A1A1A" : "#F5F6F8",
      borderRadius: 999,
      paddingHorizontal: 9,
      paddingVertical: 3,
      overflow: "hidden",
    },
    menuCategoryItems: {
      gap: 8,
    },
    menuCategoryItem: {
      paddingVertical: 7,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: isDark ? "#222" : "rgba(12,12,14,0.08)",
    },
    menuCategoryItemName: {
      color: COLORS.textPrimary,
      fontSize: 13,
      fontWeight: "800",
    },
    menuCategoryItemMeta: {
      color: COLORS.textSecondary,
      fontSize: 11,
      fontWeight: "600",
      marginTop: 3,
    },
    menuCategoryMoreText: {
      color: COLORS.textTertiary,
      fontSize: 11,
      fontWeight: "700",
      marginTop: 2,
    },

    reviewsHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 14,
      marginTop: 8,
    },
    seeAllText: {
      color: "#FFD700",
      fontSize: 12,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    addReviewText: {
      color: "#32D74B",
      fontSize: 12,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    emptyReviews: { paddingVertical: 30, alignItems: "center" },
    emptyReviewsText: { color: COLORS.textSecondary, fontSize: 14, fontWeight: "600" },
    classMeetingList: {
      gap: 10,
      marginBottom: 12,
    },
    classMeetingCard: {
      borderRadius: 18,
      padding: 14,
      gap: 6,
      backgroundColor: isDark ? "#111" : "#FFFFFF",
      borderWidth: 1,
      borderColor: isDark ? "#222" : "rgba(12,12,14,0.08)",
    },
    classMeetingHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    classMeetingCode: {
      color: COLORS.textPrimary,
      fontSize: 14,
      fontWeight: "800",
      flex: 1,
    },
    classMeetingTime: {
      color: "#500000",
      fontSize: 12,
      fontWeight: "800",
    },
    classMeetingName: {
      color: COLORS.textPrimary,
      fontSize: 13,
      fontWeight: "700",
    },
    classMeetingMeta: {
      color: COLORS.textSecondary,
      fontSize: 12,
      lineHeight: 18,
    },
    classMeetingScheduleLabel: {
      color: COLORS.textSecondary,
      fontSize: 11,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.4,
    },

    // ── Review Modal ────────────────────────────────────────────────────────
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.85)",
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
    },
    reviewModalContainer: {
      width: "100%",
      backgroundColor: "#121212",
      borderRadius: 24,
      padding: 24,
      borderWidth: 1,
      borderColor: "#222",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.5,
      shadowRadius: 20,
      elevation: 12,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
    },
    modalTitle: { fontSize: 22, fontWeight: "800", color: "#FFF" },
    starRow: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 12,
      marginBottom: 24,
    },
    starTouch: { padding: 4 },
    inputContainer: { marginBottom: 24 },
    reviewInput: {
      backgroundColor: "#1A1A1A",
      borderRadius: 16,
      padding: 16,
      color: "#FFF",
      fontSize: 16,
      height: 120,
      textAlignVertical: "top",
      borderWidth: 1,
      borderColor: "#333",
    },
    charCount: {
      position: "absolute",
      bottom: 10,
      right: 12,
      fontSize: 10,
      color: "#555",
    },
    premiumPostBtn: {
      backgroundColor: "#FFD700",
      borderRadius: 16,
      paddingVertical: 18,
      alignItems: "center",
    },
    premiumPostBtnText: {
      color: "#000",
      fontSize: 17,
      fontWeight: "800",
      letterSpacing: 0.5,
    },
    btnContent: { flexDirection: "row", alignItems: "center", gap: 8 },

    // ── Full Reviews Modal ──────────────────────────────────────────────────
    fullReviewsOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.58)",
      justifyContent: "flex-end",
    },
    fullReviewsContainer: {
      maxHeight: SCREEN_HEIGHT * 0.74,
      backgroundColor: isDark ? "rgba(12,12,14,0.98)" : "rgba(255,255,255,0.98)",
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      borderTopWidth: 1,
      borderTopColor: isDark ? "#1F1F1F" : "rgba(12,12,14,0.08)",
      paddingTop: 10,
    },
    fullReviewsHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 18,
      paddingBottom: 14,
      borderBottomWidth: 1,
      borderBottomColor: isDark ? "#222" : "rgba(12,12,14,0.08)",
    },
    fullReviewsTitle: {
      fontSize: 18,
      fontWeight: "800",
      color: COLORS.textPrimary,
    },
    fullReviewsSubtitle: {
      color: COLORS.textSecondary,
      fontSize: 12,
      fontWeight: "600",
      marginTop: 3,
    },
    fullReviewsLoading: {
      paddingVertical: 36,
      alignItems: "center",
      justifyContent: "center",
      gap: 12,
    },
    fullReviewsLoadingText: {
      color: COLORS.textSecondary,
      fontWeight: "600",
    },
    fullReviewsScroll: {
      paddingHorizontal: 18,
      paddingBottom: 44,
    },
    backBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: isDark ? "#111" : "#F3F4F7",
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: isDark ? "#333" : "rgba(12,12,14,0.08)",
    },

    // ── Transit Styles ──────────────────────────────────────────────────────
    busRouteSelectorOuter: {
      position: "absolute",
      top: 108,
      left: 16,
      width: "68%",
      alignSelf: "flex-start",
      zIndex: 3000,
      gap: 6,
    },
    busRouteSelectorRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    busRouteDropdownTrigger: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: isDark
        ? "rgba(12, 12, 14, 0.92)"
        : "rgba(255,255,255,0.96)",
      borderRadius: 14,
      paddingVertical: 7,
      paddingHorizontal: 9,
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(12,12,14,0.08)",
      gap: 8,
      flex: 1,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.18,
      shadowRadius: 5,
      elevation: 7,
    },
    selectedRouteBadge: {
      width: 28,
      height: 28,
      borderRadius: 9,
      backgroundColor: "#500000",
      alignItems: "center",
      justifyContent: "center",
    },
    selectedRouteBadgeMuted: {
      backgroundColor: isDark ? "rgba(255,255,255,0.12)" : "rgba(12,12,14,0.72)",
    },
    selectedRouteNumber: {
      color: "#FFF",
      fontSize: 11,
      fontWeight: "900",
    },
    selectedRouteTextStack: {
      flex: 1,
      justifyContent: "center",
    },
    labelSubText: {
      color: COLORS.textTertiary,
      fontSize: 9,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: 1,
    },
    selectedRouteName: {
      color: COLORS.textPrimary,
      fontSize: 11,
      fontWeight: "800",
    },
    chevronIcon: {
      paddingHorizontal: 6,
    },
    busTimetableButton: {
      width: 34,
      height: 34,
      borderRadius: 11,
      backgroundColor: isDark
        ? "rgba(12, 12, 14, 0.92)"
        : "rgba(255,255,255,0.98)",
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(12,12,14,0.12)",
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.18,
      shadowRadius: 6,
      elevation: 6,
    },
    destinationSearchCard: {
      backgroundColor: isDark ? "rgba(12,12,14,0.92)" : "rgba(255,255,255,0.97)",
      borderRadius: 18,
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(12,12,14,0.08)",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.24,
      shadowRadius: 10,
      elevation: 8,
      overflow: "hidden",
    },
    destinationSearchRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    destinationSearchInput: {
      flex: 1,
      color: COLORS.textPrimary,
      fontSize: 14,
      fontWeight: "600",
    },
    destinationResults: {
      borderTopWidth: 1,
      borderTopColor: COLORS.border,
      paddingVertical: 6,
      paddingHorizontal: 10,
      gap: 8,
    },
    destinationResultItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    destinationResultMain: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingVertical: 8,
      paddingHorizontal: 4,
    },
    destinationResultTitle: {
      color: COLORS.textPrimary,
      fontSize: 13,
      fontWeight: "800",
    },
    destinationResultMeta: {
      color: COLORS.textSecondary,
      fontSize: 11,
      fontWeight: "600",
      marginTop: 1,
    },
    destinationModePill: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: COLORS.border,
      backgroundColor: isDark ? "rgba(255,255,255,0.06)" : "rgba(12,12,14,0.04)",
    },
    destinationModeText: {
      color: COLORS.textPrimary,
      fontSize: 11,
      fontWeight: "700",
    },
    destinationEmptyText: {
      color: COLORS.textSecondary,
      fontSize: 12,
      fontWeight: "600",
      paddingHorizontal: 4,
      paddingVertical: 8,
    },
    busRoutesDropdown: {
      marginTop: 6,
      maxHeight: 220,
      backgroundColor: isDark ? "rgba(12,12,14,0.96)" : "rgba(255,255,255,0.98)",
      borderRadius: 16,
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(12,12,14,0.08)",
      overflow: "hidden",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.22,
      shadowRadius: 16,
      elevation: 12,
    },
    busDropdownScroll: {
      paddingVertical: 8,
    },
    routeSearchRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 14,
      paddingTop: 14,
      paddingBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: COLORS.border,
    },
    placesListOverlay: {
      position: "absolute",
      top: 124,
      left: 16,
      right: 16,
      bottom: FLOATING_CARD_BOTTOM_OFFSET + 88,
      zIndex: 3400,
      alignItems: "stretch",
    },
    placesListOverlaySchedule: {
      top: 238,
    },
    placesSheet: {
      position: "absolute",
      left: 14,
      right: 14,
      bottom: 12,
      zIndex: 3600,
      borderRadius: 24,
      backgroundColor: isDark ? "rgba(12, 12, 14, 0.96)" : "rgba(255, 255, 255, 0.98)",
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(12,12,14,0.08)",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 16 },
      shadowOpacity: 0.24,
      shadowRadius: 24,
      elevation: 18,
      overflow: "hidden",
    },
    placesSheetHandleZone: {
      paddingTop: 8,
      paddingHorizontal: 16,
      paddingBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: isDark ? "rgba(255,255,255,0.06)" : "rgba(12,12,14,0.06)",
    },
    placesSheetHandle: {
      width: 46,
      height: 5,
      borderRadius: 999,
      backgroundColor: isDark ? "rgba(255,255,255,0.18)" : "rgba(12,12,14,0.16)",
      alignSelf: "center",
      marginBottom: 10,
    },
    placesSheetHeader: {
      gap: 4,
    },
    placesSheetTitleRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 12,
    },
    placesSheetTitle: {
      color: COLORS.textPrimary,
      fontSize: 17,
      fontWeight: "900",
      letterSpacing: -0.3,
    },
    placesSheetSubtitle: {
      color: COLORS.textSecondary,
      fontSize: 11,
      lineHeight: 16,
      marginTop: 2,
    },
    placesSheetCountPill: {
      alignSelf: "flex-start",
      backgroundColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(12,12,14,0.06)",
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    placesSheetCountText: {
      color: COLORS.textPrimary,
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 0.2,
    },
    placesSheetCloseButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: isDark ? "rgba(255,255,255,0.07)" : "rgba(12,12,14,0.06)",
      marginTop: -12, // Moved further up as requested
    },
    placesSheetCloseText: {
      color: COLORS.textPrimary,
      fontSize: 24,
      fontWeight: "500",
      lineHeight: 24,
      marginTop: -2,
    },
    placesSheetBody: {
      flex: 1,
    },
    placesSheetScheduleCard: {
      borderRadius: 18,
      padding: 12,
      marginHorizontal: 16,
      marginTop: 10,
      marginBottom: 8,
      backgroundColor: isDark ? "rgba(255,255,255,0.03)" : "rgba(12,12,14,0.03)",
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(12,12,14,0.06)",
      gap: 12,
    },
    placesSheetScheduleTopRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 12,
    },
    placesSheetScheduleIcon: {
      width: 42,
      height: 42,
      borderRadius: 21,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: COLORS.primary,
      flexShrink: 0,
    },
    placesSheetScheduleEyebrow: {
      color: COLORS.textSecondary,
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.7,
      marginBottom: 3,
    },
    placesSheetScheduleTitle: {
      color: COLORS.textPrimary,
      fontSize: 15,
      fontWeight: "900",
      lineHeight: 20,
    },
    placesSheetScheduleBody: {
      color: COLORS.textSecondary,
      fontSize: 11,
      lineHeight: 15,
      marginTop: 3,
    },
    placesSheetScheduleMenuButton: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: isDark ? "rgba(255,255,255,0.06)" : "rgba(12,12,14,0.05)",
    },
    placesSheetScheduleActionRow: {
      flexDirection: "row",
      gap: 10,
    },
    placesSheetScheduleAction: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      flex: 1,
      minHeight: 40,
      borderRadius: 16,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(12,12,14,0.08)",
      backgroundColor: isDark ? "rgba(255,255,255,0.04)" : "#FFF",
    },
    placesSheetScheduleActionPrimary: {
      backgroundColor: COLORS.primary,
      borderColor: COLORS.primary,
    },
    placesSheetScheduleActionText: {
      color: COLORS.textPrimary,
      fontSize: 12,
      fontWeight: "800",
    },
    placesSheetScheduleActionPrimaryText: {
      color: "#FFFFFF",
      fontSize: 12,
      fontWeight: "800",
    },
    placesSheetScheduleChipScroller: {
      gap: 10,
      paddingRight: 4,
    },
    placesSheetScheduleChip: {
      minWidth: 132,
      maxWidth: 180,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(12,12,14,0.08)",
      backgroundColor: isDark ? "#121214" : "#F6F4F1",
      gap: 3,
    },
    placesSheetScheduleChipActive: {
      backgroundColor: "#500000",
      borderColor: "#500000",
    },
    placesSheetScheduleChipLabel: {
      color: COLORS.textPrimary,
      fontSize: 12,
      fontWeight: "800",
    },
    placesSheetScheduleChipLabelActive: {
      color: "#FFFFFF",
    },
    placesSheetScheduleChipMeta: {
      color: COLORS.textSecondary,
      fontSize: 10,
      fontWeight: "600",
    },
    placesSheetScheduleChipMetaActive: {
      color: "rgba(255,255,255,0.78)",
    },
    placesSheetCollapsedBody: {
      minHeight: 74,
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 10,
      justifyContent: "center",
    },
    placesSheetCollapsedSummary: {
      borderRadius: 16,
      paddingHorizontal: 12,
      paddingVertical: 9,
      backgroundColor: isDark ? "rgba(255,255,255,0.04)" : "rgba(12,12,14,0.03)",
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.06)" : "rgba(12,12,14,0.05)",
      gap: 4,
    },
    placesSheetCollapsedSummaryTitle: {
      color: COLORS.textPrimary,
      fontSize: 13,
      fontWeight: "800",
    },
    placesSheetCollapsedSummaryMeta: {
      color: COLORS.textSecondary,
      fontSize: 11,
      fontWeight: "600",
    },
    placesSheetScroll: {
      flex: 1,
    },
    placesSheetListContent: {
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 22,
    },
    placesSheetItemCard: {
      marginBottom: 6,
    },
    placesSheetItemCardCompact: {
      marginBottom: 6,
    },
    placesSheetItemPressable: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 10,
    },
    placesSheetItemIcon: {
      width: 36,
      height: 36,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: COLORS.primary,
      flexShrink: 0,
    },
    placesSheetItemBody: {
      flex: 1,
      minWidth: 0,
    },
    placesSheetItemTagRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 4,
    },
    placesSheetItemTag: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 999,
      backgroundColor: isDark ? "rgba(255,255,255,0.07)" : "rgba(12,12,14,0.06)",
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.06)" : "rgba(12,12,14,0.05)",
    },
    placesSheetItemTagText: {
      color: COLORS.textPrimary,
      fontSize: 10,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.4,
    },
    placesSheetItemTagMeta: {
      flex: 1,
      color: COLORS.textSecondary,
      fontSize: 10,
      fontWeight: "700",
    },
    placesSheetItemHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 12,
      marginBottom: 3,
    },
    placesSheetItemTitle: {
      flex: 1,
      color: COLORS.textPrimary,
      fontSize: 13,
      fontWeight: "800",
    },
    placesSheetItemDistance: {
      color: COLORS.textSecondary,
      fontSize: 10,
      fontWeight: "800",
    },
    placesSheetItemMeta: {
      color: COLORS.textSecondary,
      fontSize: 11,
      lineHeight: 15,
    },
    placesSheetItemStatusRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
      marginTop: 7,
    },
    placesSheetItemStatusChip: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 999,
      backgroundColor: isDark ? "rgba(255,255,255,0.05)" : "rgba(12,12,14,0.05)",
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.05)" : "rgba(12,12,14,0.05)",
    },
    placesSheetItemStatusChipText: {
      color: COLORS.textPrimary,
      fontSize: 10,
      fontWeight: "700",
    },
    placesSheetItemHint: {
      color: COLORS.textPrimary,
      fontSize: 10,
      lineHeight: 14,
      marginTop: 5,
    },
    placesListCard: {
      flex: 1,
      paddingBottom: 6,
      backgroundColor: isDark ? '#141416' : '#FFFFFF',
      borderWidth: 1,
      borderColor: isDark ? '#27272A' : '#DADCE0',
      borderRadius: 22,
    },
    placesListHeader: {
      marginBottom: 8,
      gap: 4,
    },
    placesListHeaderRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 12,
    },
    placesListTitle: {
      color: COLORS.textPrimary,
      fontSize: 16,
      fontWeight: "800",
    },
    placesListSubtitle: {
      color: COLORS.textSecondary,
      fontSize: 12,
      lineHeight: 18,
    },
    placesListExitButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: isDark ? "#27272A" : "#DADCE0",
      backgroundColor: isDark ? "#18181B" : "#F7F8FA",
    },
    placesListExitText: {
      color: COLORS.textPrimary,
      fontSize: 12,
      fontWeight: "800",
    },
    placesListContent: {
      paddingBottom: 16,
      gap: 10,
    },
    placesListRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: COLORS.border,
    },
    placesListIcon: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: COLORS.primary,
    },
    placesListRowHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      marginBottom: 4,
    },
    placesListRowTitle: {
      color: COLORS.textPrimary,
      fontSize: 14,
      fontWeight: "800",
      flex: 1,
    },
    placesListRowDistance: {
      color: COLORS.textSecondary,
      fontSize: 11,
      fontWeight: "700",
    },
    placesListRowMeta: {
      color: COLORS.textSecondary,
      fontSize: 12,
      lineHeight: 18,
    },
    placesListParkingHint: {
      color: COLORS.textPrimary,
      fontSize: 11,
      lineHeight: 16,
      marginTop: 5,
    },
    routeSearchInput: {
      flex: 1,
      color: COLORS.textPrimary,
      fontSize: 14,
      fontWeight: "600",
      paddingVertical: 0,
    },
    emptyRouteSearchState: {
      paddingHorizontal: 16,
      paddingVertical: 22,
      gap: 6,
    },
    emptyRouteSearchTitle: {
      color: COLORS.textPrimary,
      fontSize: 14,
      fontWeight: "800",
    },
    emptyRouteSearchBody: {
      color: COLORS.textSecondary,
      fontSize: 12,
      lineHeight: 18,
    },
    busRouteItem: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderBottomWidth: 1,
      borderBottomColor: COLORS.border,
    },
    busRouteItemActive: {
      backgroundColor: isDark ? "rgba(128,0,0,0.1)" : "rgba(80,0,0,0.08)",
    },
    routeItemBadge: {
      minWidth: 36,
      paddingHorizontal: 6,
      height: 32,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 12,
    },
    routeItemBadgeActive: {
      backgroundColor: COLORS.primary,
    },
    routeItemBadgeIdle: {
      backgroundColor: isDark ? "#1A1A1A" : "#EFF1F5",
      borderWidth: isDark ? 0 : 1,
      borderColor: isDark ? "transparent" : "rgba(12,12,14,0.08)",
    },
    routeItemNumber: {
      color: "#FFF",
      fontSize: 12,
      fontWeight: "800",
    },
    routeItemNumberIdle: {
      color: isDark ? "#FFF" : COLORS.textPrimary,
    },
    routeItemName: {
      flex: 1,
      color: COLORS.textSecondary,
      fontSize: 14,
      fontWeight: "600",
    },
    routeItemNameActive: {
      color: COLORS.textPrimary,
      fontWeight: "800",
    },
    activeCheckDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: "#F3F1ED",
      marginLeft: 8,
    },
    busTransitPanel: {
      backgroundColor: "rgba(12,12,14,0.88)",
      borderRadius: 28,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.08)",
      padding: 16,
      gap: 14,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.22,
      shadowRadius: 14,
      elevation: 10,
    },
    busTransitHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    busTransitTitle: {
      color: "#FFF",
      fontSize: 15,
      fontWeight: "800",
    },
    busTransitSubtitle: {
      color: "#A6A6AC",
      fontSize: 12,
      marginTop: 2,
    },
    nearbyTransitCard: {
      backgroundColor: "rgba(255,255,255,0.04)",
      borderRadius: 20,
      padding: 14,
      gap: 6,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.05)",
    },
    nearbyTransitCardMuted: {
      backgroundColor: "rgba(255,255,255,0.03)",
      borderRadius: 20,
      padding: 14,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.04)",
    },
    nearbyTransitTitle: {
      color: "#FFF",
      fontSize: 13,
      fontWeight: "800",
    },
    nearbyTransitBody: {
      color: "#D2D2D7",
      fontSize: 12,
      lineHeight: 18,
    },
    nearbyTransitMutedText: {
      color: "#A6A6AC",
      fontSize: 12,
      lineHeight: 18,
    },
    stopBoardHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    stopBoardTitle: {
      color: "#FFF",
      fontSize: 13,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.6,
    },
    stopBoardMeta: {
      color: "#A6A6AC",
      fontSize: 11,
      fontWeight: "700",
    },
    stopBoardList: {
      gap: 8,
    },
    stopBoardRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 12,
      paddingVertical: 12,
      backgroundColor: "rgba(255,255,255,0.04)",
      borderRadius: 18,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.05)",
    },
    stopBoardSequence: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: "rgba(255,255,255,0.08)",
      alignItems: "center",
      justifyContent: "center",
    },
    stopBoardSequenceText: {
      color: "#F3F1ED",
      fontSize: 11,
      fontWeight: "800",
    },
    stopBoardName: {
      color: "#FFF",
      fontSize: 13,
      fontWeight: "700",
    },
    stopBoardDetail: {
      color: "#9A9AA0",
      fontSize: 11,
      marginTop: 2,
    },
    stopBoardEta: {
      color: "#F3F1ED",
      fontSize: 12,
      fontWeight: "800",
    },
    circularActionBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: "#007AFF",
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 5,
      elevation: 6,
    },
    busMarker: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: "#800000",
      borderWidth: 2,
      borderColor: "#FFD700", // Gold border for visibility
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.8,
      shadowRadius: 4,
      elevation: 6,
    },
    userLocationMarker: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: "rgba(255,255,255,0.24)",
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.65)",
    },
    userLocationInner: {
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: "#4DA3FF",
      borderWidth: 2,
      borderColor: "#FFFFFF",
    },
    busMarkerText: {
      color: "#FFF",
      fontSize: 12,
      fontWeight: "900",
    },
    busStopPin: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: "#007AFF", // Standard Blue
      borderWidth: 2,
      borderColor: "#FFF",
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 4,
    },
    busStopInfoCard: {
      position: "absolute",
      bottom: FLOATING_CARD_BOTTOM_OFFSET + 12,
      left: 20,
      right: 20,
      backgroundColor: "rgba(12, 12, 12, 0.98)",
      borderRadius: 24,
      padding: 20,
      borderWidth: 1,
      borderColor: "#800000",
      zIndex: 2000,
      flexDirection: "row",
      alignItems: "center",
      gap: 16,
    },
    stopInfoIcon: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: "#007AFF",
      alignItems: "center",
      justifyContent: "center",
    },
    stopInfoName: {
      color: "#FFF",
      fontSize: 16,
      fontWeight: "800",
      marginBottom: 2,
    },
    stopInfoProximity: {
      color: "#FFD700",
      fontSize: 13,
      fontWeight: "700",
    },
    busVehicleInfoCard: {
      position: "absolute",
      bottom: FLOATING_CARD_BOTTOM_OFFSET + 12,
      left: 20,
      right: 20,
      backgroundColor: isDark ? "rgba(18, 18, 20, 0.90)" : "rgba(255,255,255,0.98)",
      borderRadius: 24,
      padding: 20,
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(12,12,14,0.08)",
      zIndex: 2000,
      flexDirection: "row",
      alignItems: "center",
      gap: 16,
    },
    busInfoIcon: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: "#800000",
      alignItems: "center",
      justifyContent: "center",
    },
    busInfoBadgeRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 4,
    },
    busInfoBadge: {
      backgroundColor: isDark ? "#333" : "#EFF1F5",
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 6,
    },
    busInfoBadgeText: {
      color: COLORS.textPrimary,
      fontSize: 11,
      fontWeight: "700",
    },
    loadBadge: {
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 6,
    },
    loadText: {
      fontSize: 11,
      fontWeight: "700",
    },
    busInfoRouteName: {
      color: COLORS.textPrimary,
      fontSize: 15,
      fontWeight: "700",
    },
    dockedStopContainer: {
      position: "absolute",
      bottom: FLOATING_CARD_BOTTOM_OFFSET,
      left: 20,
      right: 20,
      zIndex: 5000, // VERY HIGH to be on top of everything
    },
    mapFabStack: {
      position: "absolute",
      right: 18,
      bottom: FLOATING_CARD_BOTTOM_OFFSET + 76,
      gap: 12,
      zIndex: 4500,
    },
    mapFab: {
      width: 54,
      height: 54,
      borderRadius: 27,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: isDark ? "rgba(18,18,20,0.92)" : "rgba(255,255,255,0.96)",
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(12,12,14,0.08)",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.22,
      shadowRadius: 14,
      elevation: 14,
    },
    busStopDockedCard: {
      backgroundColor: isDark ? "rgba(18,18,20,0.90)" : "rgba(255,255,255,0.98)",
      borderRadius: 20,
      padding: 16,
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(12,12,14,0.08)",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.5,
      shadowRadius: 15,
      elevation: 10,
    },
    stopIconCircular: {
      width: 44,
      color: COLORS.textSecondary,
      fontSize: 12,
      fontWeight: "600",
      marginBottom: 6,
    },
    proximityRow: {
      flexDirection: "row",
      alignItems: "center",
    },
    dockedStopProximity: {
      color: "#007AFF",
      fontSize: 13,
      fontWeight: "700",
    },
    closeStopBtn: {
      padding: 8,
    },

    // ── Map Markers ──────────────────────────────────────────────────────────
    busStopMarker: {
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: "rgba(0,122,255,0.2)",
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1.5,
      borderColor: "#007AFF",
    },
    busStopMarkerInner: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: "#007AFF",
    },
    busVehicleMarker: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: "#800000",
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: "#FFD700",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.6,
      shadowRadius: 4,
      elevation: 5,
    },
    busVehicleMarkerInner: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: "#FFD700",
    },
    markerPin: {
      width: 32,
      height: 32,
      borderRadius: 16,
      justifyContent: "center",
      alignItems: "center",
      zIndex: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      elevation: 6,
    },
    markerPinLeg: {
      width: 0,
      height: 0,
      borderLeftWidth: 6,
      borderRightWidth: 6,
      borderTopWidth: 10,
      borderLeftColor: "transparent",
      borderRightColor: "transparent",
      marginTop: -2,
      zIndex: 1,
    },
    // ── Numbered Pin styles ──────────────────────────────────
    numberedPinContainer: {
      alignItems: "center",
      justifyContent: "center",
      zIndex: 10,
    },
    numberedPinHead: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: "#FFFFFF",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    numberedPinNumber: {
      color: "#FFFFFF",
      fontSize: 14,
      fontWeight: "bold",
    },
    numberedPinTail: {
      width: 0,
      height: 0,
      borderLeftWidth: 6,
      borderRightWidth: 6,
      borderTopWidth: 10,
      borderLeftColor: "transparent",
      borderRightColor: "transparent",
      marginTop: -4,
    },
    // ── Date Navigation ──────────────────────────────────────
    dateNavHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 8,
    },
    dateNavArrow: {
      padding: 6,
    },
    dateNavTitleContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 24,
    },
    dateNavTitle: {
      fontSize: 14,
      fontWeight: "800",
      color: COLORS.textPrimary,
    },
    // ── Next Up Card ─────────────────────────────────────────
    nextUpCard: {
      padding: 0,
      backgroundColor: "transparent",
    },
    nextUpEyebrow: {
      fontSize: 12,
      fontWeight: "700",
      color: COLORS.primary,
      textTransform: "uppercase",
      letterSpacing: 1.2,
      marginBottom: 12,
    },
    nextUpMainRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 2,
    },
    nextUpTimeBox: {
      width: 32,
      height: 32,
      borderRadius: 8,
      backgroundColor: "rgba(128, 0, 0, 0.08)",
      alignItems: "center",
      justifyContent: "center",
      marginRight: 10,
    },
    nextUpTimeText: {
      fontSize: 10,
      fontWeight: "700",
      color: COLORS.primary,
      textAlign: "center",
    },
    nextUpContent: {
      flex: 1,
    },
    nextUpTitle: {
      fontSize: 14,
      fontWeight: "700",
      color: COLORS.textPrimary,
      marginBottom: 1,
    },
    nextUpLocation: {
      fontSize: 12,
      color: COLORS.textSecondary,
    },
    nextUpHintBox: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "rgba(0,122,255,0.06)",
      paddingVertical: 2,
      paddingHorizontal: 6,
      borderRadius: 4,
      marginBottom: 0,
    },
    nextUpHintText: {
      fontSize: 12,
      color: "#007AFF",
      fontWeight: "600",
      marginLeft: 6,
    },
    nextUpExpandButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: COLORS.primary,
      paddingVertical: 12,
      borderRadius: 12,
      gap: 8,
    },
    nextUpExpandText: {
      color: "#FFFFFF",
      fontSize: 15,
      fontWeight: "700",
    },
    // ── Top-mounted Today Overlay ────────────────────────────
    todayTopOverlay: {
      position: "absolute",
      left: 0,
      right: 0,
      paddingHorizontal: 16,
    },
    todayTopContainer: {
      backgroundColor: isDark ? "rgba(20, 20, 22, 0.95)" : "rgba(255, 255, 255, 0.95)",
      borderRadius: 12,
      padding: 2,
      borderWidth: 1,
      borderColor: isDark ? "rgba(255, 255, 255, 0.1)" : "rgba(0, 0, 0, 0.05)",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 16,
      elevation: 8,
    },
  });
